### PR TITLE
TEN-111 Fireflies.ai Integration

### PR DESCRIPTION
**Pull request by frandominguezl**

### CODE REVIEW

**Comment by rubentrf** [comment]
The meeting owner is not disclosed in the participants, would it be possible to fetch it maybe from the speakers?

image
_(see as I'm not mentioned in the participants, also, the bot is)_

image
_(the correct info seems to be included in the Speakers section)_

**Comment by rubentrf** [comment]
The rest of the code and task looks quite nice. :tada: 

In the near future, we would want to persist the meeting information in the database, and not call the API every time to retrieve the data, but I'd rather do that when we integrate the next meeting source (either Teams or Google Meet).

**Comment by frandominguezl** [comment]
It's possible to display the organizer email, yes. I would say, place it in another column next to Meeting Duration?

As for persisting the information in the database, shouldn't be difficult at all given how easy is to create migrations.

**Comment by rubentrf** [comment]
I possible, put the organizer next to the rest of attendees, maybe just in first position. If it's too complicated, add it in a different column.

**Comment by rubentrf** [comment]
Can be merged :rocket:

**Pull request merged**
